name: Docker Production
on:
  push:
    branches:
      - master
env:
  VERSION: $(node -e "console.log(require('./package.json').version)")
  IMAGE_NAME: deadeokdevelopergroup/thikira-back-end
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: thikira
  HEROKU_IMAGE: registry.heroku.com/thikira/web
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: authenticating Docker repositry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: build Docker Image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: tag Docker Image with Latest
        run: docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.IMAGE_NAME }}:latest
      - name: push Docker Image tagged Latest
        run: docker push ${{ env.IMAGE_NAME }}:latest
